use std::fmt::Write;

use crate::types::storage::TableDef;
use crate::utils;

pub fn generate_diesel_model(table: &TableDef) -> String {
    let mut out = String::new();
    writeln!(out, "// AUTO-GENERATED by namma-dsl-rs. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use diesel::prelude::*;").unwrap();
    writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();
    writeln!(out, "use crate::storage::schema::{};", table.table_name_sql).unwrap();
    if !table.kv_disabled {
        writeln!(out, "use shared::db::kv::KvEntity;").unwrap();
        writeln!(
            out,
            "use crate::domain::types::{}::{};",
            table.table_name_sql, table.table_name_rust
        )
        .unwrap();
    }
    writeln!(out).unwrap();

    let enum_names: Vec<String> = table.types.iter().map(|t| t.name.clone()).collect();
    let model_name = format!("{}Model", table.table_name_rust);

    writeln!(
        out,
        "#[derive(Debug, Clone, Queryable, Selectable, Insertable, Serialize, Deserialize)]"
    )
    .unwrap();
    writeln!(out, "#[diesel(table_name = {})]", table.table_name_sql).unwrap();
    writeln!(out, "#[diesel(check_for_backend(diesel::pg::Pg))]").unwrap();
    writeln!(out, "pub struct {} {{", model_name).unwrap();
    for f in &table.fields {
        let db_type = utils::domain_type_to_db_type(&f.rust_type, &enum_names);
        writeln!(out, "    pub {}: {},", f.field_name_snake, db_type).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    if !table.kv_disabled {
        emit_kv_entity_impl(&mut out, table, &model_name);
    }

    out
}

fn emit_kv_entity_impl(out: &mut String, table: &TableDef, model_name: &str) {
    let domain_name = &table.table_name_rust;

    writeln!(out, "impl KvEntity for {} {{", model_name).unwrap();
    writeln!(out, "    type DomainType = {};", domain_name).unwrap();
    writeln!(
        out,
        "    fn table_name() -> &'static str {{ \"{}\" }}",
        table.table_name_sql
    )
    .unwrap();

    let pk_fields: Vec<&_> = table.fields.iter().filter(|f| f.is_primary_key).collect();
    writeln!(out, "    fn primary_key(&self) -> String {{").unwrap();
    if pk_fields.len() == 1 {
        let snake = &pk_fields[0].field_name_snake;
        writeln!(out, "        self.{}.clone()", snake).unwrap();
    } else if pk_fields.is_empty() {
        writeln!(out, "        String::new()").unwrap(); // no PK; KV will be unused
    } else {
        let parts: Vec<String> = pk_fields
            .iter()
            .map(|f| format!("self.{}", f.field_name_snake))
            .collect();
        writeln!(
            out,
            "        format!(\"{}\", {})",
            vec!["{}"; pk_fields.len()].join(":"),
            parts.join(", ")
        )
        .unwrap();
    }
    writeln!(out, "    }}").unwrap();

    if !table.secondary_keys.is_empty() {
        writeln!(
            out,
            "    fn secondary_indexes(&self) -> Vec<(&'static str, String)> {{"
        )
        .unwrap();
        writeln!(out, "        vec![").unwrap();
        for sk in &table.secondary_keys {
            for col in sk {
                let snake = utils::to_snake(col);
                writeln!(
                    out,
                    "            (\"{}\", self.{}.clone()),",
                    snake, snake
                )
                .unwrap();
            }
        }
        writeln!(out, "        ]").unwrap();
        writeln!(out, "    }}").unwrap();
    }

    writeln!(out, "}}").unwrap();
}
