use std::fmt::Write;

use crate::types::storage::TableDef;
use crate::utils;

/// Generate the `diesel::table!` macro invocation for a single table.
pub fn generate_diesel_schema(table: &TableDef, type_mappings: &[(String, String)]) -> String {
    let mut out = String::new();
    writeln!(out, "// AUTO-GENERATED by namma-dsl-rs. Do not edit.").unwrap();
    writeln!(out).unwrap();

    let enum_names: Vec<String> = table.types.iter().map(|t| t.name.clone()).collect();

    let pk_cols: Vec<String> = table
        .primary_key
        .iter()
        .map(|pk| utils::to_snake(pk))
        .collect();
    let pk_str = if pk_cols.is_empty() {
        "id".to_string()
    } else {
        pk_cols.join(", ")
    };

    writeln!(out, "diesel::table! {{").unwrap();
    writeln!(out, "    {} ({}) {{", table.table_name_sql, pk_str).unwrap();

    for f in &table.fields {
        let diesel_type = utils::rust_type_to_diesel_type(&f.rust_type, &enum_names, type_mappings);
        writeln!(out, "        {} -> {},", f.field_name_snake, diesel_type).unwrap();
    }

    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    out
}
