use std::fmt::Write;

use crate::types::storage::TableDef;
use crate::utils;

/// Generate the Diesel model structs (Queryable + Insertable) for a single table.
pub fn generate_diesel_model(table: &TableDef) -> String {
    let mut out = String::new();
    writeln!(out, "// AUTO-GENERATED by namma-dsl-rs. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use diesel::prelude::*;").unwrap();
    writeln!(out, "use crate::storage::schema::{};", table.table_name_sql).unwrap();
    writeln!(out).unwrap();

    let enum_names: Vec<String> = table.types.iter().map(|t| t.name.clone()).collect();
    let model_name = format!("{}Model", table.table_name_rust);
    let new_name = format!("New{}", table.table_name_rust);

    // Queryable + Selectable struct
    writeln!(out, "#[derive(Debug, Clone, Queryable, Selectable)]").unwrap();
    writeln!(out, "#[diesel(table_name = {})]", table.table_name_sql).unwrap();
    writeln!(out, "#[diesel(check_for_backend(diesel::pg::Pg))]").unwrap();
    writeln!(out, "pub struct {} {{", model_name).unwrap();
    for f in &table.fields {
        let db_type = utils::domain_type_to_db_type(&f.rust_type, &enum_names);
        writeln!(out, "    pub {}: {},", f.field_name_snake, db_type).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Insertable struct
    writeln!(out, "#[derive(Debug, Clone, Insertable)]").unwrap();
    writeln!(out, "#[diesel(table_name = {})]", table.table_name_sql).unwrap();
    writeln!(out, "pub struct {} {{", new_name).unwrap();
    for f in &table.fields {
        let db_type = utils::domain_type_to_db_type(&f.rust_type, &enum_names);
        writeln!(out, "    pub {}: {},", f.field_name_snake, db_type).unwrap();
    }
    writeln!(out, "}}").unwrap();

    out
}
