use std::collections::HashSet;
use std::fmt::Write;

use crate::types::storage::TableDef;
use crate::utils;

/// Generate the domain type Rust source file for a single table.
pub fn generate_domain_type(table: &TableDef) -> String {
    let mut out = String::new();
    writeln!(out, "// AUTO-GENERATED by namma-dsl-rs. Do not edit.").unwrap();
    writeln!(out).unwrap();

    let mut needed_imports: HashSet<String> = HashSet::new();
    let mut needs_serde = false;
    let mut needs_chrono = false;

    for d in &table.derives {
        if d == "Serialize" || d == "Deserialize" {
            needs_serde = true;
        }
    }

    for f in &table.fields {
        if f.rust_type.contains("chrono::") {
            needs_chrono = true;
        }
        collect_type_imports(&f.rust_type, &table.imports, &mut needed_imports);
    }

    if needs_serde {
        writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();
    }
    if needs_chrono {
        writeln!(out, "use chrono;").unwrap();
    }

    let enum_names: Vec<String> = table.types.iter().map(|t| t.name.clone()).collect();
    for f in &table.fields {
        if utils::is_id_type(&f.rust_type) && !needed_imports.contains("Id") {
            needed_imports.insert("Id".to_string());
        }
    }

    if needed_imports.contains("Id") {
        writeln!(out, "use crate::types::id::Id;").unwrap();
    }

    let mut sorted_imports: Vec<_> = needed_imports
        .iter()
        .filter(|i| *i != "Id")
        .filter(|i| !enum_names.contains(i))
        .cloned()
        .collect();
    sorted_imports.sort();

    for imp in &sorted_imports {
        if let Some(path) = table.imports.get(imp) {
            writeln!(out, "use {}::{};", path, imp).unwrap();
        }
    }

    writeln!(out).unwrap();

    // Enums first
    for ty in &table.types {
        if ty.is_enum {
            let mut all_derives = vec![
                "Debug".to_string(),
                "Clone".to_string(),
                "PartialEq".to_string(),
                "Eq".to_string(),
                "Serialize".to_string(),
                "Deserialize".to_string(),
            ];
            for d in &ty.derives {
                if !all_derives.contains(d) {
                    all_derives.push(d.clone());
                }
            }
            writeln!(out, "#[derive({})]", all_derives.join(", ")).unwrap();
            writeln!(out, "pub enum {} {{", ty.name).unwrap();
            for v in &ty.variants {
                writeln!(out, "    {},", v).unwrap();
            }
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();

            // Display impl for enum -> string serialization
            writeln!(out, "impl std::fmt::Display for {} {{", ty.name).unwrap();
            writeln!(
                out,
                "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{"
            )
            .unwrap();
            writeln!(out, "        match self {{").unwrap();
            for v in &ty.variants {
                writeln!(
                    out,
                    "            {}::{} => write!(f, \"{}\"),",
                    ty.name, v, v
                )
                .unwrap();
            }
            writeln!(out, "        }}").unwrap();
            writeln!(out, "    }}").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();

            // FromStr impl for parsing from DB strings
            writeln!(out, "impl std::str::FromStr for {} {{", ty.name).unwrap();
            writeln!(out, "    type Err = String;").unwrap();
            writeln!(out).unwrap();
            writeln!(
                out,
                "    fn from_str(s: &str) -> Result<Self, Self::Err> {{"
            )
            .unwrap();
            writeln!(out, "        match s {{").unwrap();
            for v in &ty.variants {
                writeln!(out, "            \"{}\" => Ok({}::{}),", v, ty.name, v).unwrap();
            }
            writeln!(
                out,
                "            _ => Err(format!(\"unknown variant: {{}}\", s)),"
            )
            .unwrap();
            writeln!(out, "        }}").unwrap();
            writeln!(out, "    }}").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
    }

    // Main struct
    let derives_str = table.derives.join(", ");
    writeln!(out, "#[derive({})]", derives_str).unwrap();
    writeln!(out, "pub struct {} {{", table.table_name_rust).unwrap();
    for f in &table.fields {
        writeln!(out, "    pub {}: {},", f.field_name_snake, f.rust_type).unwrap();
    }
    writeln!(out, "}}").unwrap();

    out
}

fn collect_type_imports(
    rust_type: &str,
    imports: &std::collections::HashMap<String, String>,
    needed: &mut HashSet<String>,
) {
    let inner = utils::unwrap_option(rust_type);
    if utils::is_id_type(inner) {
        let id_inner = utils::extract_id_inner(inner);
        if imports.contains_key(id_inner) {
            needed.insert(id_inner.to_string());
        }
    } else if imports.contains_key(inner) {
        needed.insert(inner.to_string());
    }
}
