use std::fmt::Write;

use crate::types::storage::*;
use crate::utils;

/// Generate the query functions and From conversion impls for a single table.
pub fn generate_queries(table: &TableDef) -> String {
    let mut out = String::new();
    let enum_names: Vec<String> = table.types.iter().map(|t| t.name.clone()).collect();
    let model_name = format!("{}Model", table.table_name_rust);
    let new_name = format!("New{}", table.table_name_rust);
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;

    writeln!(out, "// AUTO-GENERATED by namma-dsl-rs. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use diesel::prelude::*;").unwrap();
    writeln!(out, "use crate::storage::schema::{};", sql_table).unwrap();
    writeln!(
        out,
        "use crate::storage::models::{}::{{{}, {}}};",
        sql_table, model_name, new_name
    )
    .unwrap();
    writeln!(
        out,
        "use crate::domain::types::{}::{};",
        sql_table, domain_name
    )
    .unwrap();

    let has_id_fields = table.fields.iter().any(|f| utils::is_id_type(&f.rust_type));
    if has_id_fields {
        writeln!(out, "use crate::types::id::Id;").unwrap();
    }

    // Import types referenced in Id<T> fields that come from other modules
    let mut extra_type_imports = std::collections::HashSet::new();
    for f in &table.fields {
        let inner = utils::unwrap_option(&f.rust_type);
        if utils::is_id_type(inner) {
            let id_inner = utils::extract_id_inner(inner);
            if id_inner != domain_name {
                if let Some(module_path) = table.imports.get(id_inner) {
                    extra_type_imports.insert((id_inner.to_string(), module_path.clone()));
                }
            }
        }
    }
    let mut sorted_extra: Vec<_> = extra_type_imports.into_iter().collect();
    sorted_extra.sort();
    for (type_name, module_path) in &sorted_extra {
        writeln!(out, "use {}::{};", module_path, type_name).unwrap();
    }
    writeln!(out).unwrap();

    // Import enum types from domain
    for ty in &table.types {
        if ty.is_enum {
            writeln!(out, "use crate::domain::types::{}::{};", sql_table, ty.name).unwrap();
        }
    }
    if !table.types.is_empty() {
        writeln!(out).unwrap();
    }

    // --- Default queries ---
    generate_create(&mut out, table);
    generate_create_many(&mut out, table);
    generate_find_by_primary_key(&mut out, table);
    generate_update_by_primary_key(&mut out, table, &enum_names);

    // --- Spec queries ---
    for q in &table.queries {
        generate_spec_query(&mut out, q, table, &enum_names);
    }

    // --- From impls ---
    generate_from_model_impl(&mut out, table, &enum_names);
    generate_to_new_impl(&mut out, table, &enum_names);

    out
}

fn generate_create(out: &mut String, table: &TableDef) {
    let new_name = format!("New{}", table.table_name_rust);
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;

    writeln!(
        out,
        "pub fn create(conn: &mut PgConnection, entity: &{}) -> QueryResult<()> {{",
        domain_name
    )
    .unwrap();
    writeln!(out, "    let new_record = {}::from(entity);", new_name).unwrap();
    writeln!(out, "    diesel::insert_into({}::table)", sql_table).unwrap();
    writeln!(out, "        .values(&new_record)").unwrap();
    writeln!(out, "        .execute(conn)?;").unwrap();
    writeln!(out, "    Ok(())").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn generate_create_many(out: &mut String, table: &TableDef) {
    let new_name = format!("New{}", table.table_name_rust);
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;

    writeln!(
        out,
        "pub fn create_many(conn: &mut PgConnection, entities: &[{}]) -> QueryResult<()> {{",
        domain_name
    )
    .unwrap();
    writeln!(
        out,
        "    let new_records: Vec<{}> = entities.iter().map({}::from).collect();",
        new_name, new_name
    )
    .unwrap();
    writeln!(out, "    diesel::insert_into({}::table)", sql_table).unwrap();
    writeln!(out, "        .values(&new_records)").unwrap();
    writeln!(out, "        .execute(conn)?;").unwrap();
    writeln!(out, "    Ok(())").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn generate_find_by_primary_key(out: &mut String, table: &TableDef) {
    let domain_name = &table.table_name_rust;
    let model_name = format!("{}Model", table.table_name_rust);
    let sql_table = &table.table_name_sql;

    let pk_fields: Vec<&FieldDef> = table.fields.iter().filter(|f| f.is_primary_key).collect();
    if pk_fields.is_empty() {
        return;
    }

    let params: Vec<String> = pk_fields.iter().map(|f| format_param(f)).collect();
    let params_str = params.join(", ");

    writeln!(
        out,
        "pub fn find_by_primary_key(conn: &mut PgConnection, {}) -> QueryResult<Option<{}>> {{",
        params_str, domain_name
    )
    .unwrap();

    if pk_fields.len() == 1 {
        let pk = &pk_fields[0];
        let val = param_to_filter_value(pk);
        writeln!(out, "    {}::table", sql_table).unwrap();
        writeln!(out, "        .find({})", val).unwrap();
        writeln!(out, "        .first::<{}>(conn)", model_name).unwrap();
        writeln!(out, "        .optional()").unwrap();
        writeln!(out, "        .map(|opt| opt.map({}::from))", domain_name).unwrap();
    } else {
        writeln!(out, "    {}::table", sql_table).unwrap();
        for pk in &pk_fields {
            let val = param_to_filter_value(pk);
            writeln!(
                out,
                "        .filter({}::{}.eq({}))",
                sql_table, pk.field_name_snake, val
            )
            .unwrap();
        }
        writeln!(out, "        .first::<{}>(conn)", model_name).unwrap();
        writeln!(out, "        .optional()").unwrap();
        writeln!(out, "        .map(|opt| opt.map({}::from))", domain_name).unwrap();
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn generate_update_by_primary_key(out: &mut String, table: &TableDef, enum_names: &[String]) {
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;

    let pk_fields: Vec<&FieldDef> = table.fields.iter().filter(|f| f.is_primary_key).collect();
    let non_pk_fields: Vec<&FieldDef> = table.fields.iter().filter(|f| !f.is_primary_key).collect();
    if pk_fields.is_empty() || non_pk_fields.is_empty() {
        return;
    }

    writeln!(
        out,
        "pub fn update_by_primary_key(conn: &mut PgConnection, entity: &{}) -> QueryResult<()> {{",
        domain_name
    )
    .unwrap();

    let has_updated_at = table
        .fields
        .iter()
        .any(|f| f.field_name_snake == "updated_at");
    if has_updated_at {
        writeln!(out, "    let now = chrono::Utc::now().naive_utc();").unwrap();
    }

    // Build target
    if pk_fields.len() == 1 {
        let pk = &pk_fields[0];
        let pk_val = entity_field_to_db_value(pk, enum_names);
        writeln!(
            out,
            "    diesel::update({}::table.find({}))",
            sql_table, pk_val
        )
        .unwrap();
    } else {
        writeln!(out, "    diesel::update({}::table", sql_table).unwrap();
        for pk in &pk_fields {
            let pk_val = entity_field_to_db_value(pk, enum_names);
            writeln!(
                out,
                "        .filter({}::{}.eq({}))",
                sql_table, pk.field_name_snake, pk_val
            )
            .unwrap();
        }
        write!(out, "    )").unwrap();
    }

    writeln!(out, "        .set((").unwrap();
    for f in &non_pk_fields {
        if f.field_name_snake == "updated_at" {
            writeln!(out, "            {}::updated_at.eq(now),", sql_table).unwrap();
        } else if f.field_name_snake == "created_at" {
            continue;
        } else {
            let val = entity_field_to_db_value(f, enum_names);
            writeln!(
                out,
                "            {}::{}.eq({}),",
                sql_table, f.field_name_snake, val
            )
            .unwrap();
        }
    }
    writeln!(out, "        ))").unwrap();
    writeln!(out, "        .execute(conn)?;").unwrap();
    writeln!(out, "    Ok(())").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn generate_spec_query(out: &mut String, q: &QueryDef, table: &TableDef, enum_names: &[String]) {
    let domain_name = &table.table_name_rust;
    let model_name = format!("{}Model", table.table_name_rust);
    let sql_table = &table.table_name_sql;

    match q.kv_function {
        KvFunction::FindOne => {
            let params = where_clause_params(&q.where_clause, table);
            let params_str = if params.is_empty() {
                String::new()
            } else {
                format!(", {}", params.join(", "))
            };

            writeln!(
                out,
                "pub fn {}(conn: &mut PgConnection{}) -> QueryResult<Option<{}>> {{",
                q.name_snake, params_str, domain_name
            )
            .unwrap();
            writeln!(out, "    {}::table", sql_table).unwrap();
            emit_where_filters(out, &q.where_clause, sql_table, table);
            if let Some(ref ob) = q.order_by {
                let dir = match ob.direction {
                    OrderDirection::Asc => "asc",
                    OrderDirection::Desc => "desc",
                };
                writeln!(
                    out,
                    "        .order({}::{}.{}())",
                    sql_table,
                    utils::to_snake(&ob.field),
                    dir
                )
                .unwrap();
            }
            writeln!(out, "        .first::<{}>(conn)", model_name).unwrap();
            writeln!(out, "        .optional()").unwrap();
            writeln!(out, "        .map(|opt| opt.map({}::from))", domain_name).unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
        KvFunction::FindOnePartial => {
            let params = where_clause_params(&q.where_clause, table);
            let params_str = if params.is_empty() {
                String::new()
            } else {
                format!(", {}", params.join(", "))
            };

            
        }
        KvFunction::FindAll => {
            let params = where_clause_params(&q.where_clause, table);
            let params_str = if params.is_empty() {
                String::new()
            } else {
                format!(", {}", params.join(", "))
            };

            writeln!(
                out,
                "pub fn {}(conn: &mut PgConnection{}) -> QueryResult<Vec<{}>> {{",
                q.name_snake, params_str, domain_name
            )
            .unwrap();
            writeln!(out, "    {}::table", sql_table).unwrap();
            emit_where_filters(out, &q.where_clause, sql_table, table);
            if let Some(ref ob) = q.order_by {
                let dir = match ob.direction {
                    OrderDirection::Asc => "asc",
                    OrderDirection::Desc => "desc",
                };
                writeln!(
                    out,
                    "        .order({}::{}.{}())",
                    sql_table,
                    utils::to_snake(&ob.field),
                    dir
                )
                .unwrap();
            }
            writeln!(out, "        .load::<{}>(conn)", model_name).unwrap();
            writeln!(
                out,
                "        .map(|rows| rows.into_iter().map({}::from).collect())",
                domain_name
            )
            .unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
        KvFunction::FindAllPartial => {

        }
        KvFunction::Update | KvFunction::UpdateOne => {
            let where_params = where_clause_params(&q.where_clause, table);
            let set_params: Vec<String> = q
                .params
                .iter()
                .filter_map(|p| {
                    table
                        .fields
                        .iter()
                        .find(|f| f.field_name == *p)
                        .map(|f| format_param(f))
                })
                .collect();
            let all_params: Vec<String> = set_params
                .iter()
                .chain(where_params.iter())
                .cloned()
                .collect();
            let params_str = if all_params.is_empty() {
                String::new()
            } else {
                format!(", {}", all_params.join(", "))
            };

            writeln!(
                out,
                "pub fn {}(conn: &mut PgConnection{}) -> QueryResult<()> {{",
                q.name_snake, params_str
            )
            .unwrap();
            writeln!(out, "    diesel::update({}::table", sql_table).unwrap();
            emit_where_filters_inline(out, &q.where_clause, sql_table, table);
            writeln!(out, "    )").unwrap();
            writeln!(out, "    .set((").unwrap();
            for p in &q.params {
                let snake = utils::to_snake(p);
                let field = table.fields.iter().find(|f| f.field_name == *p);
                if let Some(f) = field {
                    let val = param_value_for_set(f, enum_names);
                    writeln!(out, "        {}::{}.eq({}),", sql_table, snake, val).unwrap();
                }
            }
            writeln!(out, "    ))").unwrap();
            writeln!(out, "    .execute(conn)?;").unwrap();
            writeln!(out, "    Ok(())").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
        KvFunction::Delete => {
            let params = where_clause_params(&q.where_clause, table);
            let params_str = if params.is_empty() {
                String::new()
            } else {
                format!(", {}", params.join(", "))
            };

            writeln!(
                out,
                "pub fn {}(conn: &mut PgConnection{}) -> QueryResult<()> {{",
                q.name_snake, params_str
            )
            .unwrap();
            writeln!(out, "    diesel::delete({}::table", sql_table).unwrap();
            emit_where_filters_inline(out, &q.where_clause, sql_table, table);
            writeln!(out, "    )").unwrap();
            writeln!(out, "    .execute(conn)?;").unwrap();
            writeln!(out, "    Ok(())").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
    }
}

// --- From<Model> for Domain ---
fn generate_from_model_impl(out: &mut String, table: &TableDef, enum_names: &[String]) {
    let model_name = format!("{}Model", table.table_name_rust);
    let domain_name = &table.table_name_rust;

    writeln!(out, "impl From<{}> for {} {{", model_name, domain_name).unwrap();
    writeln!(out, "    fn from(model: {}) -> Self {{", model_name).unwrap();
    writeln!(out, "        {} {{", domain_name).unwrap();

    for f in &table.fields {
        let conversion = model_field_to_domain(f, enum_names);
        writeln!(out, "            {}: {},", f.field_name_snake, conversion).unwrap();
    }

    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

// --- From<&Domain> for NewModel ---
fn generate_to_new_impl(out: &mut String, table: &TableDef, enum_names: &[String]) {
    let new_name = format!("New{}", table.table_name_rust);
    let domain_name = &table.table_name_rust;

    writeln!(out, "impl From<&{}> for {} {{", domain_name, new_name).unwrap();
    writeln!(out, "    fn from(domain: &{}) -> Self {{", domain_name).unwrap();
    writeln!(out, "        {} {{", new_name).unwrap();

    for f in &table.fields {
        let conversion = domain_field_to_model(f, enum_names);
        writeln!(out, "            {}: {},", f.field_name_snake, conversion).unwrap();
    }

    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}

// --- Helpers ---

fn format_param(f: &FieldDef) -> String {
    if f.rust_type.starts_with("Option<") {
        let inner = utils::unwrap_option(&f.rust_type);
        if utils::is_id_type(inner) {
            let id_inner = utils::extract_id_inner(inner);
            format!("{}: Option<&Id<{}>>", f.field_name_snake, id_inner)
        } else {
            format!("{}: Option<&{}>", f.field_name_snake, inner)
        }
    } else if utils::is_id_type(&f.rust_type) {
        let id_inner = utils::extract_id_inner(&f.rust_type);
        format!("{}: &Id<{}>", f.field_name_snake, id_inner)
    } else if f.rust_type == "String" {
        format!("{}: &str", f.field_name_snake)
    } else if utils::is_vec_type(&f.rust_type) {
        format!("{}: &{}", f.field_name_snake, f.rust_type)
    } else {
        format!("{}: {}", f.field_name_snake, f.rust_type)
    }
}

fn param_to_filter_value(f: &FieldDef) -> String {
    if utils::is_id_type(&f.rust_type) {
        format!("{}.inner()", f.field_name_snake)
    } else {
        f.field_name_snake.clone()
    }
}

fn entity_field_to_db_value(f: &FieldDef, enum_names: &[String]) -> String {
    let snake = &f.field_name_snake;
    let inner_type = utils::unwrap_option(&f.rust_type);

    if f.is_nullable && utils::is_id_type(inner_type) {
        format!("entity.{}.as_ref().map(|id| id.inner().to_string())", snake)
    } else if utils::is_id_type(inner_type) {
        format!("entity.{}.inner().to_string()", snake)
    } else if f.is_nullable && enum_names.contains(&inner_type.to_string()) {
        format!("entity.{}.as_ref().map(|e| e.to_string())", snake)
    } else if enum_names.contains(&inner_type.to_string()) {
        format!("entity.{}.to_string()", snake)
    } else if inner_type == "chrono::DateTime<chrono::Utc>" {
        if f.is_nullable {
            format!("entity.{}.map(|dt| dt.naive_utc())", snake)
        } else {
            format!("entity.{}.naive_utc()", snake)
        }
    } else if f.rust_type == "String" {
        format!("entity.{}.clone()", snake)
    } else if f.is_nullable && f.rust_type.contains("String") {
        format!("entity.{}.clone()", snake)
    } else {
        format!("entity.{}", snake)
    }
}

fn param_value_for_set(f: &FieldDef, enum_names: &[String]) -> String {
    let inner = utils::unwrap_option(&f.rust_type);
    if utils::is_id_type(inner) {
        if f.is_nullable {
            format!("{}.map(|id| id.inner().to_string())", f.field_name_snake)
        } else {
            format!("{}.inner().to_string()", f.field_name_snake)
        }
    } else if enum_names.contains(&inner.to_string()) {
        if f.is_nullable {
            format!("{}.map(|e| e.to_string())", f.field_name_snake)
        } else {
            format!("{}.to_string()", f.field_name_snake)
        }
    } else {
        f.field_name_snake.clone()
    }
}

fn model_field_to_domain(f: &FieldDef, enum_names: &[String]) -> String {
    let snake = &f.field_name_snake;
    let inner = utils::unwrap_option(&f.rust_type);

    if f.is_nullable && utils::is_id_type(inner) {
        format!("model.{}.map(Id::new)", snake)
    } else if utils::is_id_type(inner) {
        format!("Id::new(model.{})", snake)
    } else if f.is_nullable && enum_names.contains(&inner.to_string()) {
        format!("model.{}.and_then(|s| s.parse().ok())", snake)
    } else if enum_names.contains(&inner.to_string()) {
        format!("model.{}.parse().expect(\"invalid enum value\")", snake)
    } else if inner == "chrono::DateTime<chrono::Utc>" {
        if f.is_nullable {
            format!("model.{}.map(|dt| dt.and_utc())", snake)
        } else {
            format!("model.{}.and_utc()", snake)
        }
    } else {
        format!("model.{}", snake)
    }
}

fn domain_field_to_model(f: &FieldDef, enum_names: &[String]) -> String {
    let snake = &f.field_name_snake;
    let inner = utils::unwrap_option(&f.rust_type);

    if f.is_nullable && utils::is_id_type(inner) {
        format!("domain.{}.as_ref().map(|id| id.inner().to_string())", snake)
    } else if utils::is_id_type(inner) {
        format!("domain.{}.inner().to_string()", snake)
    } else if f.is_nullable && enum_names.contains(&inner.to_string()) {
        format!("domain.{}.as_ref().map(|e| e.to_string())", snake)
    } else if enum_names.contains(&inner.to_string()) {
        format!("domain.{}.to_string()", snake)
    } else if inner == "chrono::DateTime<chrono::Utc>" {
        if f.is_nullable {
            format!("domain.{}.map(|dt| dt.naive_utc())", snake)
        } else {
            format!("domain.{}.naive_utc()", snake)
        }
    } else if f.rust_type == "String" {
        format!("domain.{}.clone()", snake)
    } else if f.is_nullable && f.rust_type.contains("String") {
        format!("domain.{}.clone()", snake)
    } else {
        format!("domain.{}", snake)
    }
}

fn where_clause_params(wc: &WhereClause, table: &TableDef) -> Vec<String> {
    match wc {
        WhereClause::Empty => vec![],
        WhereClause::Leaf(field_name) => {
            if let Some(f) = table.fields.iter().find(|f| f.field_name == *field_name) {
                vec![format_param(f)]
            } else {
                vec![format!("{}: &str", utils::to_snake(field_name))]
            }
        }
        WhereClause::And(clauses) | WhereClause::Or(clauses) => clauses
            .iter()
            .flat_map(|c| where_clause_params(c, table))
            .collect(),
        WhereClause::In(fields) => fields
            .iter()
            .filter_map(|field_name| {
                table
                    .fields
                    .iter()
                    .find(|f| f.field_name == *field_name)
                    .map(|f| {
                        let inner = utils::unwrap_option(&f.rust_type);
                        if utils::is_id_type(inner) {
                            let id_inner = utils::extract_id_inner(inner);
                            format!("{}: &[Id<{}>]", f.field_name_snake, id_inner)
                        } else {
                            format!("{}: &[{}]", f.field_name_snake, inner)
                        }
                    })
            })
            .collect(),
    }
}

fn emit_where_filters(out: &mut String, wc: &WhereClause, sql_table: &str, table: &TableDef) {
    match wc {
        WhereClause::Empty => {}
        WhereClause::Leaf(field_name) => {
            let snake = utils::to_snake(field_name);
            let f = table.fields.iter().find(|f| f.field_name == *field_name);
            let val = if let Some(f) = f {
                param_to_filter_value(f)
            } else {
                snake.clone()
            };
            writeln!(out, "        .filter({}::{}.eq({}))", sql_table, snake, val).unwrap();
        }
        WhereClause::And(clauses) => {
            for c in clauses {
                emit_where_filters(out, c, sql_table, table);
            }
        }
        WhereClause::Or(clauses) => {
            if clauses.len() >= 2 {
                write!(out, "        .filter(").unwrap();
                for (i, c) in clauses.iter().enumerate() {
                    if i > 0 {
                        write!(out, ".or(").unwrap();
                    }
                    emit_or_leaf(out, c, sql_table, table);
                    if i > 0 {
                        write!(out, ")").unwrap();
                    }
                }
                writeln!(out, ")").unwrap();
            }
        }
        WhereClause::In(fields) => {
            for field_name in fields {
                let snake = utils::to_snake(field_name);
                let f = table.fields.iter().find(|f| f.field_name == *field_name);
                let val = if let Some(f) = f {
                    if utils::is_id_type(&f.rust_type) {
                        format!(
                            "{}.iter().map(|id| id.inner().to_string()).collect::<Vec<_>>()",
                            snake
                        )
                    } else {
                        snake.clone()
                    }
                } else {
                    snake.clone()
                };
                writeln!(
                    out,
                    "        .filter({}::{}.eq_any({}))",
                    sql_table, snake, val
                )
                .unwrap();
            }
        }
    }
}

fn emit_or_leaf(out: &mut String, wc: &WhereClause, sql_table: &str, table: &TableDef) {
    if let WhereClause::Leaf(field_name) = wc {
        let snake = utils::to_snake(field_name);
        let f = table.fields.iter().find(|f| f.field_name == *field_name);
        let val = if let Some(f) = f {
            param_to_filter_value(f)
        } else {
            snake.clone()
        };
        write!(out, "{}::{}.eq({})", sql_table, snake, val).unwrap();
    }
}

fn emit_where_filters_inline(
    out: &mut String,
    wc: &WhereClause,
    sql_table: &str,
    table: &TableDef,
) {
    emit_where_filters(out, wc, sql_table, table);
}
