use std::fmt::Write;

use crate::types::storage::*;
use crate::utils;

pub fn generate_queries(table: &TableDef) -> String {
    let mut out = String::new();
    let enum_names: Vec<String> = table.types.iter().map(|t| t.name.clone()).collect();
    let model_name = format!("{}Model", table.table_name_rust);
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;

    emit_header(&mut out, table, &model_name);

    if table.kv_disabled {
        emit_raw_defaults(&mut out, table, &enum_names);
    } else {
        emit_kv_defaults(&mut out, table, &enum_names);
    }

    for q in &table.queries {
        emit_spec_query(&mut out, q, table, &enum_names);
    }

    emit_from_model_impl(&mut out, table, &enum_names);
    emit_to_model_impl(&mut out, table, &enum_names);

    let _ = (sql_table, domain_name);
    out
}

fn emit_header(out: &mut String, table: &TableDef, model_name: &str) {
    let sql_table = &table.table_name_sql;
    let domain_name = &table.table_name_rust;

    writeln!(out, "// AUTO-GENERATED by namma-dsl-rs. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use diesel::prelude::*;").unwrap();
    writeln!(out, "use diesel_async::RunQueryDsl;").unwrap();
    writeln!(out, "use std::pin::Pin;").unwrap();
    writeln!(out, "use shared::db::error::DbError;").unwrap();
    writeln!(out, "use shared::db::pool::DbPool;").unwrap();
    if !table.kv_disabled {
        writeln!(out, "use shared::db::kv::{{create_with_kv, find_one_with_kv, update_with_kv, delete_with_kv, MeshConfig, KvEntity}};").unwrap();
        writeln!(out, "use shared::redis::types::RedisConnectionPool;").unwrap();
    }
    writeln!(out, "use crate::storage::schema::{};", sql_table).unwrap();
    writeln!(out, "use crate::storage::models::{}::{};", sql_table, model_name).unwrap();
    writeln!(
        out,
        "use crate::domain::types::{}::{};",
        sql_table, domain_name
    )
    .unwrap();

    let has_id_fields = table.fields.iter().any(|f| utils::is_id_type(&f.rust_type));
    if has_id_fields {
        writeln!(out, "use crate::types::id::Id;").unwrap();
    }

    let mut extra_type_imports = std::collections::HashSet::new();
    for f in &table.fields {
        let inner = utils::unwrap_option(&f.rust_type);
        if utils::is_id_type(inner) {
            let id_inner = utils::extract_id_inner(inner);
            if id_inner != domain_name {
                if let Some(module_path) = table.imports.get(id_inner) {
                    extra_type_imports.insert((id_inner.to_string(), module_path.clone()));
                }
            }
        }
    }
    let mut sorted_extra: Vec<_> = extra_type_imports.into_iter().collect();
    sorted_extra.sort();
    for (type_name, module_path) in &sorted_extra {
        writeln!(out, "use {}::{};", module_path, type_name).unwrap();
    }

    for ty in &table.types {
        if ty.is_enum {
            writeln!(out, "use crate::domain::types::{}::{};", sql_table, ty.name).unwrap();
        }
    }
    writeln!(out).unwrap();
}

fn emit_kv_defaults(out: &mut String, table: &TableDef, enum_names: &[String]) {
    emit_create_kv(out, table, enum_names);
    emit_find_by_pk_kv(out, table, enum_names);
    emit_update_by_pk_kv(out, table, enum_names);
}

fn emit_raw_defaults(out: &mut String, table: &TableDef, enum_names: &[String]) {
    emit_create_raw(out, table);
    emit_find_by_pk_raw(out, table, enum_names);
    emit_update_by_pk_raw(out, table, enum_names);
}

fn emit_create_kv(out: &mut String, table: &TableDef, _enum_names: &[String]) {
    let model_name = format!("{}Model", table.table_name_rust);
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;

    writeln!(
        out,
        "pub async fn create(pool: &DbPool, redis: &RedisConnectionPool, mesh: &MeshConfig, entity: &{}) -> Result<(), DbError> {{",
        domain_name
    ).unwrap();
    writeln!(out, "    let model: {} = entity.into();", model_name).unwrap();
    writeln!(
        out,
        "    create_with_kv::<{}, _>(pool, redis, mesh, model, |conn, m| {{",
        model_name
    )
    .unwrap();
    writeln!(out, "        Box::pin(async move {{").unwrap();
    writeln!(
        out,
        "            diesel::insert_into({}::table)",
        sql_table
    )
    .unwrap();
    writeln!(out, "                .values(m)").unwrap();
    writeln!(out, "                .execute(conn)").unwrap();
    writeln!(out, "                .await").unwrap();
    writeln!(out, "                .map_err(DbError::from)?;").unwrap();
    writeln!(out, "            Ok(())").unwrap();
    writeln!(out, "        }})").unwrap();
    writeln!(out, "    }}).await").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_find_by_pk_kv(out: &mut String, table: &TableDef, enum_names: &[String]) {
    let model_name = format!("{}Model", table.table_name_rust);
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;

    let pk_fields: Vec<&FieldDef> = table.fields.iter().filter(|f| f.is_primary_key).collect();
    if pk_fields.len() != 1 {
        return; // KV PK lookup only supports single-column PK in v1
    }
    let pk = pk_fields[0];
    let pk_param = format_param(pk);
    let pk_filter = param_to_filter_value(pk, enum_names);

    writeln!(
        out,
        "pub async fn find_by_primary_key(pool: &DbPool, redis: &RedisConnectionPool, mesh: &MeshConfig, {}) -> Result<Option<{}>, DbError> {{",
        pk_param, domain_name
    ).unwrap();
    writeln!(
        out,
        "    let pk_owned = {}.to_string();",
        pk_filter
    )
    .unwrap();
    writeln!(
        out,
        "    let key = {}::redis_pk_key(&pk_owned);",
        model_name
    )
    .unwrap();
    writeln!(
        out,
        "    find_one_with_kv::<{}, _>(pool, redis, mesh, &key, move |conn| {{",
        model_name
    )
    .unwrap();
    writeln!(out, "        Box::pin(async move {{").unwrap();
    writeln!(out, "            {}::table", sql_table).unwrap();
    writeln!(out, "                .find(pk_owned)").unwrap();
    writeln!(out, "                .first::<{}>(conn)", model_name).unwrap();
    writeln!(out, "                .await").unwrap();
    writeln!(out, "                .optional()").unwrap();
    writeln!(out, "                .map_err(DbError::from)").unwrap();
    writeln!(out, "        }})").unwrap();
    writeln!(out, "    }}).await").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_update_by_pk_kv(out: &mut String, table: &TableDef, enum_names: &[String]) {
    let model_name = format!("{}Model", table.table_name_rust);
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;

    let pk_fields: Vec<&FieldDef> = table.fields.iter().filter(|f| f.is_primary_key).collect();
    let non_pk: Vec<&FieldDef> = table.fields.iter().filter(|f| !f.is_primary_key).collect();
    if pk_fields.len() != 1 || non_pk.is_empty() {
        return;
    }
    let pk = pk_fields[0];

    writeln!(
        out,
        "pub async fn update_by_primary_key(pool: &DbPool, redis: &RedisConnectionPool, mesh: &MeshConfig, entity: &{}) -> Result<(), DbError> {{",
        domain_name
    ).unwrap();
    writeln!(out, "    let entity = entity.clone();").unwrap(); // clone so closure owns
    writeln!(
        out,
        "    let key = {}::redis_pk_key(&entity.{}.to_string());",
        model_name, pk.field_name_snake
    )
    .unwrap();
    let pk_db_val = entity_field_to_db_value(pk, enum_names);
    writeln!(
        out,
        "    update_with_kv::<{}, _>(pool, redis, mesh, &[&key], move |conn| {{",
        model_name
    )
    .unwrap();
    writeln!(out, "        Box::pin(async move {{").unwrap();
    writeln!(
        out,
        "            diesel::update({}::table.find({}))",
        sql_table, pk_db_val
    )
    .unwrap();
    writeln!(out, "                .set((").unwrap();
    let has_updated_at = table
        .fields
        .iter()
        .any(|f| f.field_name_snake == "updated_at");
    if has_updated_at {
        writeln!(
            out,
            "                    {}::updated_at.eq(chrono::Utc::now().naive_utc()),",
            sql_table
        )
        .unwrap();
    }
    for f in &non_pk {
        if f.field_name_snake == "updated_at" || f.field_name_snake == "created_at" {
            continue;
        }
        let val = entity_field_to_db_value(f, enum_names);
        writeln!(
            out,
            "                    {}::{}.eq({}),",
            sql_table, f.field_name_snake, val
        )
        .unwrap();
    }
    writeln!(out, "                ))").unwrap();
    writeln!(out, "                .execute(conn)").unwrap();
    writeln!(out, "                .await").unwrap();
    writeln!(out, "                .map_err(DbError::from)?;").unwrap();
    writeln!(out, "            Ok(())").unwrap();
    writeln!(out, "        }})").unwrap();
    writeln!(out, "    }}).await").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_create_raw(out: &mut String, table: &TableDef) {
    let model_name = format!("{}Model", table.table_name_rust);
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;
    writeln!(
        out,
        "pub async fn create(pool: &DbPool, entity: &{}) -> Result<(), DbError> {{",
        domain_name
    )
    .unwrap();
    writeln!(out, "    let model: {} = entity.into();", model_name).unwrap();
    writeln!(out, "    let mut conn = pool.get().await?;").unwrap();
    writeln!(out, "    diesel::insert_into({}::table)", sql_table).unwrap();
    writeln!(out, "        .values(&model)").unwrap();
    writeln!(out, "        .execute(&mut *conn)").unwrap();
    writeln!(out, "        .await").unwrap();
    writeln!(out, "        .map_err(DbError::from)?;").unwrap();
    writeln!(out, "    Ok(())").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_find_by_pk_raw(out: &mut String, table: &TableDef, enum_names: &[String]) {
    let model_name = format!("{}Model", table.table_name_rust);
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;
    let pk_fields: Vec<&FieldDef> = table.fields.iter().filter(|f| f.is_primary_key).collect();
    if pk_fields.is_empty() {
        return;
    }
    let params: Vec<String> = pk_fields.iter().map(|f| format_param(f)).collect();
    writeln!(
        out,
        "pub async fn find_by_primary_key(pool: &DbPool, {}) -> Result<Option<{}>, DbError> {{",
        params.join(", "),
        domain_name
    )
    .unwrap();
    writeln!(out, "    let mut conn = pool.get().await?;").unwrap();
    writeln!(out, "    {}::table", sql_table).unwrap();
    for pk in &pk_fields {
        let val = param_to_filter_value(pk, enum_names);
        writeln!(
            out,
            "        .filter({}::{}.eq({}))",
            sql_table, pk.field_name_snake, val
        )
        .unwrap();
    }
    writeln!(out, "        .first::<{}>(&mut *conn)", model_name).unwrap();
    writeln!(out, "        .await").unwrap();
    writeln!(out, "        .optional()").unwrap();
    writeln!(out, "        .map(|opt| opt.map({}::from))", domain_name).unwrap();
    writeln!(out, "        .map_err(DbError::from)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_update_by_pk_raw(out: &mut String, table: &TableDef, enum_names: &[String]) {
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;
    let pk_fields: Vec<&FieldDef> = table.fields.iter().filter(|f| f.is_primary_key).collect();
    let non_pk: Vec<&FieldDef> = table.fields.iter().filter(|f| !f.is_primary_key).collect();
    if pk_fields.is_empty() || non_pk.is_empty() {
        return;
    }
    writeln!(
        out,
        "pub async fn update_by_primary_key(pool: &DbPool, entity: &{}) -> Result<(), DbError> {{",
        domain_name
    )
    .unwrap();
    writeln!(out, "    let mut conn = pool.get().await?;").unwrap();
    let pk = pk_fields[0];
    let pk_val = entity_field_to_db_value(pk, enum_names);
    writeln!(
        out,
        "    diesel::update({}::table.find({}))",
        sql_table, pk_val
    )
    .unwrap();
    writeln!(out, "        .set((").unwrap();
    let has_updated_at = table
        .fields
        .iter()
        .any(|f| f.field_name_snake == "updated_at");
    if has_updated_at {
        writeln!(
            out,
            "            {}::updated_at.eq(chrono::Utc::now().naive_utc()),",
            sql_table
        )
        .unwrap();
    }
    for f in &non_pk {
        if f.field_name_snake == "updated_at" || f.field_name_snake == "created_at" {
            continue;
        }
        let val = entity_field_to_db_value(f, enum_names);
        writeln!(
            out,
            "            {}::{}.eq({}),",
            sql_table, f.field_name_snake, val
        )
        .unwrap();
    }
    writeln!(out, "        ))").unwrap();
    writeln!(out, "        .execute(&mut *conn)").unwrap();
    writeln!(out, "        .await").unwrap();
    writeln!(out, "        .map_err(DbError::from)?;").unwrap();
    writeln!(out, "    Ok(())").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_spec_query(out: &mut String, q: &QueryDef, table: &TableDef, enum_names: &[String]) {
    let model_name = format!("{}Model", table.table_name_rust);
    let domain_name = &table.table_name_rust;
    let sql_table = &table.table_name_sql;

    match q.kv_function {
        KvFunction::FindOne | KvFunction::FindOnePartial => {
            let params = where_clause_params(&q.where_clause, table);
            let params_str = if params.is_empty() {
                String::new()
            } else {
                format!(", {}", params.join(", "))
            };
            writeln!(
                out,
                "pub async fn {}(pool: &DbPool{}) -> Result<Option<{}>, DbError> {{",
                q.name_snake, params_str, domain_name
            )
            .unwrap();
            writeln!(out, "    let mut conn = pool.get().await?;").unwrap();
            writeln!(out, "    {}::table", sql_table).unwrap();
            emit_where_filters(out, &q.where_clause, sql_table, table);
            if let Some(ref ob) = q.order_by {
                let dir = match ob.direction {
                    OrderDirection::Asc => "asc",
                    OrderDirection::Desc => "desc",
                };
                writeln!(
                    out,
                    "        .order({}::{}.{}())",
                    sql_table,
                    utils::to_snake(&ob.field),
                    dir
                )
                .unwrap();
            }
            writeln!(out, "        .first::<{}>(&mut *conn)", model_name).unwrap();
            writeln!(out, "        .await").unwrap();
            writeln!(out, "        .optional()").unwrap();
            writeln!(out, "        .map(|opt| opt.map({}::from))", domain_name).unwrap();
            writeln!(out, "        .map_err(DbError::from)").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
        KvFunction::FindAll | KvFunction::FindAllPartial => {
            let params = where_clause_params(&q.where_clause, table);
            let params_str = if params.is_empty() {
                String::new()
            } else {
                format!(", {}", params.join(", "))
            };
            writeln!(
                out,
                "pub async fn {}(pool: &DbPool{}) -> Result<Vec<{}>, DbError> {{",
                q.name_snake, params_str, domain_name
            )
            .unwrap();
            writeln!(out, "    let mut conn = pool.get().await?;").unwrap();
            writeln!(out, "    {}::table", sql_table).unwrap();
            emit_where_filters(out, &q.where_clause, sql_table, table);
            if let Some(ref ob) = q.order_by {
                let dir = match ob.direction {
                    OrderDirection::Asc => "asc",
                    OrderDirection::Desc => "desc",
                };
                writeln!(
                    out,
                    "        .order({}::{}.{}())",
                    sql_table,
                    utils::to_snake(&ob.field),
                    dir
                )
                .unwrap();
            }
            writeln!(out, "        .load::<{}>(&mut *conn)", model_name).unwrap();
            writeln!(out, "        .await").unwrap();
            writeln!(
                out,
                "        .map(|rows| rows.into_iter().map({}::from).collect())",
                domain_name
            )
            .unwrap();
            writeln!(out, "        .map_err(DbError::from)").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
        KvFunction::Update | KvFunction::UpdateOne => {
            let where_params = where_clause_params(&q.where_clause, table);
            let set_params: Vec<String> = q
                .params
                .iter()
                .filter_map(|p| {
                    table
                        .fields
                        .iter()
                        .find(|f| f.field_name == *p)
                        .map(format_param)
                })
                .collect();
            let all_params: Vec<String> = set_params
                .iter()
                .chain(where_params.iter())
                .cloned()
                .collect();
            let params_str = if all_params.is_empty() {
                String::new()
            } else {
                format!(", {}", all_params.join(", "))
            };
            writeln!(
                out,
                "pub async fn {}(pool: &DbPool{}) -> Result<(), DbError> {{",
                q.name_snake, params_str
            )
            .unwrap();
            writeln!(out, "    let mut conn = pool.get().await?;").unwrap();
            writeln!(out, "    diesel::update({}::table", sql_table).unwrap();
            emit_where_filters(out, &q.where_clause, sql_table, table);
            writeln!(out, "    )").unwrap();
            writeln!(out, "    .set((").unwrap();
            for p in &q.params {
                let snake = utils::to_snake(p);
                if let Some(f) = table.fields.iter().find(|f| f.field_name == *p) {
                    let val = param_value_for_set(f, enum_names);
                    writeln!(out, "        {}::{}.eq({}),", sql_table, snake, val).unwrap();
                }
            }
            writeln!(out, "    ))").unwrap();
            writeln!(out, "    .execute(&mut *conn)").unwrap();
            writeln!(out, "    .await").unwrap();
            writeln!(out, "    .map_err(DbError::from)?;").unwrap();
            writeln!(out, "    Ok(())").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
        KvFunction::Delete => {
            let params = where_clause_params(&q.where_clause, table);
            let params_str = if params.is_empty() {
                String::new()
            } else {
                format!(", {}", params.join(", "))
            };
            writeln!(
                out,
                "pub async fn {}(pool: &DbPool{}) -> Result<(), DbError> {{",
                q.name_snake, params_str
            )
            .unwrap();
            writeln!(out, "    let mut conn = pool.get().await?;").unwrap();
            writeln!(out, "    diesel::delete({}::table", sql_table).unwrap();
            emit_where_filters(out, &q.where_clause, sql_table, table);
            writeln!(out, "    )").unwrap();
            writeln!(out, "    .execute(&mut *conn)").unwrap();
            writeln!(out, "    .await").unwrap();
            writeln!(out, "    .map_err(DbError::from)?;").unwrap();
            writeln!(out, "    Ok(())").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
    }
    let _ = (model_name, delete_with_kv_stub());
}

fn delete_with_kv_stub() -> &'static str {
    "" // referenced from import block; emission of delete_with_kv via spec queries is future scope
}

fn emit_from_model_impl(out: &mut String, table: &TableDef, enum_names: &[String]) {
    let model_name = format!("{}Model", table.table_name_rust);
    let domain_name = &table.table_name_rust;

    writeln!(out, "impl From<{}> for {} {{", model_name, domain_name).unwrap();
    writeln!(out, "    fn from(model: {}) -> Self {{", model_name).unwrap();
    writeln!(out, "        {} {{", domain_name).unwrap();
    for f in &table.fields {
        let conversion = model_field_to_domain(f, enum_names);
        writeln!(out, "            {}: {},", f.field_name_snake, conversion).unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_to_model_impl(out: &mut String, table: &TableDef, enum_names: &[String]) {
    let model_name = format!("{}Model", table.table_name_rust);
    let domain_name = &table.table_name_rust;

    writeln!(out, "impl From<&{}> for {} {{", domain_name, model_name).unwrap();
    writeln!(out, "    fn from(domain: &{}) -> Self {{", domain_name).unwrap();
    writeln!(out, "        {} {{", model_name).unwrap();
    for f in &table.fields {
        let conversion = domain_field_to_model(f, enum_names);
        writeln!(out, "            {}: {},", f.field_name_snake, conversion).unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}

fn format_param(f: &FieldDef) -> String {
    if f.rust_type.starts_with("Option<") {
        let inner = utils::unwrap_option(&f.rust_type);
        if utils::is_id_type(inner) {
            let id_inner = utils::extract_id_inner(inner);
            format!("{}: Option<&Id<{}>>", f.field_name_snake, id_inner)
        } else {
            format!("{}: Option<&{}>", f.field_name_snake, inner)
        }
    } else if utils::is_id_type(&f.rust_type) {
        let id_inner = utils::extract_id_inner(&f.rust_type);
        format!("{}: &Id<{}>", f.field_name_snake, id_inner)
    } else if f.rust_type == "String" {
        format!("{}: &str", f.field_name_snake)
    } else if utils::is_vec_type(&f.rust_type) {
        format!("{}: &{}", f.field_name_snake, f.rust_type)
    } else {
        format!("{}: {}", f.field_name_snake, f.rust_type)
    }
}

fn param_to_filter_value(f: &FieldDef, enum_names: &[String]) -> String {
    let inner = utils::unwrap_option(&f.rust_type);
    if utils::is_id_type(&f.rust_type) {
        format!("{}.inner()", f.field_name_snake)
    } else if enum_names.contains(&inner.to_string()) {
        format!("{}.to_string()", f.field_name_snake)
    } else {
        f.field_name_snake.clone()
    }
}

fn entity_field_to_db_value(f: &FieldDef, enum_names: &[String]) -> String {
    let snake = &f.field_name_snake;
    let inner_type = utils::unwrap_option(&f.rust_type);

    if f.is_nullable && utils::is_id_type(inner_type) {
        format!("entity.{}.as_ref().map(|id| id.inner().to_string())", snake)
    } else if utils::is_id_type(inner_type) {
        format!("entity.{}.inner().to_string()", snake)
    } else if f.is_nullable && enum_names.contains(&inner_type.to_string()) {
        format!("entity.{}.as_ref().map(|e| e.to_string())", snake)
    } else if enum_names.contains(&inner_type.to_string()) {
        format!("entity.{}.to_string()", snake)
    } else if inner_type == "chrono::DateTime<chrono::Utc>" {
        if f.is_nullable {
            format!("entity.{}.map(|dt| dt.naive_utc())", snake)
        } else {
            format!("entity.{}.naive_utc()", snake)
        }
    } else if f.rust_type == "String" {
        format!("entity.{}.clone()", snake)
    } else if f.is_nullable && f.rust_type.contains("String") {
        format!("entity.{}.clone()", snake)
    } else {
        format!("entity.{}", snake)
    }
}

fn param_value_for_set(f: &FieldDef, enum_names: &[String]) -> String {
    let inner = utils::unwrap_option(&f.rust_type);
    if utils::is_id_type(inner) {
        if f.is_nullable {
            format!("{}.map(|id| id.inner().to_string())", f.field_name_snake)
        } else {
            format!("{}.inner().to_string()", f.field_name_snake)
        }
    } else if enum_names.contains(&inner.to_string()) {
        if f.is_nullable {
            format!("{}.map(|e| e.to_string())", f.field_name_snake)
        } else {
            format!("{}.to_string()", f.field_name_snake)
        }
    } else {
        f.field_name_snake.clone()
    }
}

fn model_field_to_domain(f: &FieldDef, enum_names: &[String]) -> String {
    let snake = &f.field_name_snake;
    let inner = utils::unwrap_option(&f.rust_type);

    if f.is_nullable && utils::is_id_type(inner) {
        format!("model.{}.map(Id::new)", snake)
    } else if utils::is_id_type(inner) {
        format!("Id::new(model.{})", snake)
    } else if f.is_nullable && enum_names.contains(&inner.to_string()) {
        format!("model.{}.and_then(|s| s.parse().ok())", snake)
    } else if enum_names.contains(&inner.to_string()) {
        format!("model.{}.parse().expect(\"invalid enum value\")", snake)
    } else if inner == "chrono::DateTime<chrono::Utc>" {
        if f.is_nullable {
            format!("model.{}.map(|dt| dt.and_utc())", snake)
        } else {
            format!("model.{}.and_utc()", snake)
        }
    } else {
        format!("model.{}", snake)
    }
}

fn domain_field_to_model(f: &FieldDef, enum_names: &[String]) -> String {
    let snake = &f.field_name_snake;
    let inner = utils::unwrap_option(&f.rust_type);

    if f.is_nullable && utils::is_id_type(inner) {
        format!("domain.{}.as_ref().map(|id| id.inner().to_string())", snake)
    } else if utils::is_id_type(inner) {
        format!("domain.{}.inner().to_string()", snake)
    } else if f.is_nullable && enum_names.contains(&inner.to_string()) {
        format!("domain.{}.as_ref().map(|e| e.to_string())", snake)
    } else if enum_names.contains(&inner.to_string()) {
        format!("domain.{}.to_string()", snake)
    } else if inner == "chrono::DateTime<chrono::Utc>" {
        if f.is_nullable {
            format!("domain.{}.map(|dt| dt.naive_utc())", snake)
        } else {
            format!("domain.{}.naive_utc()", snake)
        }
    } else if f.rust_type == "String" {
        format!("domain.{}.clone()", snake)
    } else if f.is_nullable && f.rust_type.contains("String") {
        format!("domain.{}.clone()", snake)
    } else {
        format!("domain.{}", snake)
    }
}

fn where_clause_params(wc: &WhereClause, table: &TableDef) -> Vec<String> {
    match wc {
        WhereClause::Empty => vec![],
        WhereClause::Leaf(field_name) => {
            if let Some(f) = table.fields.iter().find(|f| f.field_name == *field_name) {
                vec![format_param(f)]
            } else {
                vec![format!("{}: &str", utils::to_snake(field_name))]
            }
        }
        WhereClause::And(clauses) | WhereClause::Or(clauses) => clauses
            .iter()
            .flat_map(|c| where_clause_params(c, table))
            .collect(),
        WhereClause::In(fields) => fields
            .iter()
            .filter_map(|field_name| {
                table
                    .fields
                    .iter()
                    .find(|f| f.field_name == *field_name)
                    .map(|f| {
                        let inner = utils::unwrap_option(&f.rust_type);
                        if utils::is_id_type(inner) {
                            let id_inner = utils::extract_id_inner(inner);
                            format!("{}: &[Id<{}>]", f.field_name_snake, id_inner)
                        } else {
                            format!("{}: &[{}]", f.field_name_snake, inner)
                        }
                    })
            })
            .collect(),
    }
}

fn emit_where_filters(out: &mut String, wc: &WhereClause, sql_table: &str, table: &TableDef) {
    let enum_names: Vec<String> = table.types.iter().map(|t| t.name.clone()).collect();
    match wc {
        WhereClause::Empty => {}
        WhereClause::Leaf(field_name) => {
            let snake = utils::to_snake(field_name);
            let f = table.fields.iter().find(|f| f.field_name == *field_name);
            let val = if let Some(f) = f {
                param_to_filter_value(f, &enum_names)
            } else {
                snake.clone()
            };
            writeln!(out, "        .filter({}::{}.eq({}))", sql_table, snake, val).unwrap();
        }
        WhereClause::And(clauses) => {
            for c in clauses {
                emit_where_filters(out, c, sql_table, table);
            }
        }
        WhereClause::Or(_) => {} // OR fallback to raw SQL is future scope
        WhereClause::In(fields) => {
            for field_name in fields {
                let snake = utils::to_snake(field_name);
                let f = table.fields.iter().find(|f| f.field_name == *field_name);
                let val = if let Some(f) = f {
                    if utils::is_id_type(&f.rust_type) {
                        format!(
                            "{}.iter().map(|id| id.inner().to_string()).collect::<Vec<_>>()",
                            snake
                        )
                    } else {
                        snake.clone()
                    }
                } else {
                    snake.clone()
                };
                writeln!(
                    out,
                    "        .filter({}::{}.eq_any({}))",
                    sql_table, snake, val
                )
                .unwrap();
            }
        }
    }
}
